import { useEffect, useState } from 'react';
import { Activity, ArrowDown, ArrowRight, Bell, Check, ChevronDown, Dumbbell, Download, Menu, ShieldCheck, Sparkles, TrendingUp, Wallet, X } from 'lucide-react';
import './landing.css';

const money = (n: number) => new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL', maximumFractionDigits: 0 }).format(n);

export function LandingPage() {
  const [students, setStudents] = useState(32);
  const [monthly, setMonthly] = useState(180);
  const [menuOpen, setMenuOpen] = useState(false);
  const [installPrompt, setInstallPrompt] = useState<any>(null);
  const [installHelp, setInstallHelp] = useState(false);
  const [visible, setVisible] = useState(false);

  useEffect(() => {
    document.title = 'FitPulse — mais clareza para cuidar dos seus alunos';
    const meta = document.querySelector('meta[name="description"]');
    meta?.setAttribute('content', 'Conheça o FitPulse: uma demonstração para organizar alunos, treinos e acompanhamento financeiro em um só lugar.');
    const onPrompt = (event: Event) => { event.preventDefault(); setInstallPrompt(event); };
    window.addEventListener('beforeinstallprompt', onPrompt);
    const observer = new IntersectionObserver(entries => entries.forEach(entry => { if (entry.isIntersecting) { entry.target.classList.add('fp-visible'); observer.unobserve(entry.target); } }), { threshold: .12 });
    document.querySelectorAll('.fp-reveal').forEach(el => observer.observe(el));
    setVisible(true);
    return () => { window.removeEventListener('beforeinstallprompt', onPrompt); observer.disconnect(); };
  }, []);

  const install = async () => {
    if (!installPrompt) { setInstallHelp(true); return; }
    await installPrompt.prompt(); setInstallPrompt(null);
  };

  return <main className="fp-landing">
    <header className="fp-header"><a className="fp-brand" href="/landing"><span className="fp-brand-icon"><Activity size={22}/></span>FitPulse</a>
      <button className="fp-menu-toggle" onClick={() => setMenuOpen(!menuOpen)} aria-label="Abrir menu">{menuOpen ? <X/> : <Menu/>}</button>
      <nav className={menuOpen ? 'fp-nav fp-nav-open' : 'fp-nav'}><a href="#recursos" onClick={() => setMenuOpen(false)}>Recursos</a><a href="#simulador" onClick={() => setMenuOpen(false)}>Simulador</a><a href="#duvidas" onClick={() => setMenuOpen(false)}>Dúvidas</a><button className="fp-install" onClick={install}><Download size={16}/> Instalar app</button><a className="fp-login" href="/">Abrir demonstração <ArrowRight size={16}/></a></nav>
    </header>
    <section className={'fp-hero ' + (visible ? 'fp-hero-ready' : '')}><div className="fp-hero-copy"><span className="fp-eyebrow"><span/> GESTÃO FITNESS EM UM SÓ LUGAR</span><h1>Mais presença no treino.<br/><em>Mais clareza na gestão.</em></h1><p>Organize alunos, treinos e acompanhamento financeiro em uma experiência simples para o dia a dia do personal.</p><div className="fp-actions"><a className="fp-primary" href="/">Conhecer demonstração <ArrowRight size={18}/></a><a className="fp-secondary" href="#recursos"><span className="fp-play">↓</span> Explorar recursos</a></div><div className="fp-proof"><span className="fp-avatars"><i>R</i><i>M</i><i>A</i></span><span>Feito para acompanhar pessoas,<br/><b>não só números.</b></span></div></div>
      <div className="fp-dashboard" aria-label="Prévia ilustrativa do painel FitPulse"><div className="fp-window"><div className="fp-window-top"><div className="fp-dots"><i/><i/><i/></div><span>FITPULSE <b>• DEMONSTRAÇÃO</b></span><span>•••</span></div><div className="fp-dash-body"><aside><div className="fp-dash-logo"><Activity/> Pulse</div><div className="fp-side-active">▦　Visão geral</div><div>♙　Alunos</div><div>♧　Treinos</div><div>◷　Financeiro</div><div>⚙　Configurações</div></aside><div className="fp-dash-main"><div className="fp-dash-greet">Visão geral <small>Hoje, seu espaço em movimento</small></div><div className="fp-kpis"><div><span>ALUNOS ATIVOS</span><b>32</b><small className="fp-positive">+4 este mês</small></div><div><span>SESSÕES NA SEMANA</span><b>86</b><small>Agenda organizada</small></div></div><div className="fp-chart-card"><div className="fp-chart-title">Frequência de treinos <small>ÚLTIMOS 7 DIAS</small></div><div className="fp-chart"><div className="fp-ylabels"><span>30</span><span>20</span><span>10</span><span>0</span></div><div className="fp-bars">{[38,58,46,77,62,92,70].map((h,i)=><div key={i}><i style={{height:`${h}%`,animationDelay:`${i*90}ms`}}/><small>{['S','T','Q','Q','S','S','D'][i]}</small></div>)}</div></div></div><div className="fp-next"><span className="fp-next-icon"><Dumbbell size={16}/></span><span><b>Próximo treino</b><small>Marina Costa · 17:30</small></span><ArrowRight size={16}/></div></div></div></div><div className="fp-float fp-float-top"><span><TrendingUp size={16}/></span><div><b>Rotina em dia</b><small>Visão rápida do seu espaço</small></div></div><div className="fp-float fp-float-bottom"><span><Check size={16}/></span><div><b>Treino acompanhado</b><small>Mais cuidado em cada etapa</small></div></div></div>
      <a className="fp-scroll" href="#recursos"><ArrowDown size={16}/> Role para explorar</a></section>

    <section className="fp-trust"><span>UMA VISÃO MAIS CLARA DE</span><b><Dumbbell/> Alunos</b><b><Activity/> Treinos</b><b><Wallet/> Financeiro</b><b><Bell/> Acompanhamento</b></section>
    <section id="recursos" className="fp-section"><div className="fp-section-heading fp-reveal"><span className="fp-eyebrow">MENOS ABAS, MAIS FOCO</span><h2>O essencial para uma rotina<br/>de treino mais organizada.</h2><p>Recursos demonstrativos para acompanhar a jornada dos seus alunos de ponta a ponta.</p></div><div className="fp-features">
      {[{icon:<Dumbbell/>,n:'01',title:'Alunos e treinos',desc:'Consulte perfis, acompanhe informações e organize planos de treino em um só lugar.'},{icon:<TrendingUp/>,n:'02',title:'Visão do negócio',desc:'Enxergue indicadores e movimentações da demonstração com mais contexto.'},{icon:<Wallet/>,n:'03',title:'Acompanhamento financeiro',desc:'Visualize mensalidades, vencimentos e registros para manter tudo no radar.'},{icon:<Sparkles/>,n:'04',title:'Apoio com inteligência artificial',desc:'Explore ferramentas de IA disponíveis na demonstração, conforme configuração.'}].map(item=><article className="fp-feature fp-reveal" key={item.n}><div className="fp-feature-top"><span className="fp-feature-icon">{item.icon}</span><small>{item.n}</small></div><h3>{item.title}</h3><p>{item.desc}</p><a href="/" aria-label={`Abrir demonstração: ${item.title}`}><ArrowRight size={18}/></a></article>)}
    </div></section>
    <section id="simulador" className="fp-simulator"><div className="fp-sim-copy fp-reveal"><span className="fp-eyebrow">PLANEJE SEU PRÓXIMO PASSO</span><h2>Uma conta simples.<br/><em>Uma visão mais nítida.</em></h2><p>Simule o faturamento bruto mensal com seus alunos. É uma estimativa informativa, não uma promessa de resultado.</p><div className="fp-sim-note"><ShieldCheck size={18}/> Ajuste os valores e explore cenários.</div></div><div className="fp-calc fp-reveal"><div className="fp-calc-head"><b>Simulador de faturamento</b><span>ESTIMATIVA</span></div><label htmlFor="fp-students">Alunos ativos <b>{students}</b></label><input id="fp-students" type="range" min="5" max="150" value={students} onChange={e=>setStudents(+e.target.value)} style={{'--range':`${(students-5)/145*100}%`} as React.CSSProperties}/><label htmlFor="fp-price">Mensalidade média <b>{money(monthly)}</b></label><input id="fp-price" type="range" min="80" max="600" step="10" value={monthly} onChange={e=>setMonthly(+e.target.value)} style={{'--range':`${(monthly-80)/520*100}%`} as React.CSSProperties}/><div className="fp-total"><small>FATURAMENTO BRUTO ESTIMADO / MÊS</small><strong>{money(students*monthly)}</strong><span>{students} alunos × {money(monthly)} · antes de custos e inadimplência</span></div></div></section>
    <section className="fp-cta"><span className="fp-cta-glow"/><span className="fp-eyebrow">EXPERIMENTE O FITPULSE</span><h2>Veja a gestão em movimento.</h2><p>Explore a demonstração e conheça as telas de alunos, treinos e financeiro.</p><a className="fp-primary" href="/">Abrir demonstração <ArrowRight size={18}/></a><small>O conteúdo exibido é demonstrativo. Consulte as configurações do app antes de usar dados reais.</small></section>
    <section id="duvidas" className="fp-faq"><div><span className="fp-eyebrow">ANTES DE COMEÇAR</span><h2>Perguntas frequentes</h2><p>Informações claras para explorar o FitPulse.</p></div><div className="fp-faq-list">{[{q:'O FitPulse já está pronto para uso comercial?',a:'Esta versão é uma demonstração do aplicativo. Antes de usar com alunos reais, revise armazenamento, autenticação, privacidade e integrações do seu ambiente.'},{q:'Meus dados ficam salvos na nuvem?',a:'A demonstração atual utiliza dados de exemplo e armazenamento local no navegador. Não insira informações pessoais reais sem configurar e validar um backend seguro.'},{q:'Como instalo no celular?',a:'Toque em “Instalar app” se o navegador oferecer a instalação. No iPhone, abra no Safari, toque em Compartilhar e escolha “Adicionar à Tela de Início”.'},{q:'Os pagamentos são cobrados automaticamente?',a:'A tela financeira ajuda a acompanhar registros. Esta demonstração não processa pagamentos nem envia cobranças automáticas.'}].map((f,i)=><details className="fp-faq-item" key={i}><summary>{f.q}<ChevronDown size={18}/></summary><p>{f.a}</p></details>)}</div></section>
    <footer className="fp-footer"><a className="fp-brand" href="#top"><span className="fp-brand-icon"><Activity size={20}/></span>FitPulse</a><span>Organização que acompanha o seu ritmo.</span><a href="/">Ir para a demonstração <ArrowRight size={15}/></a><small>© {new Date().getFullYear()} FitPulse · Página informativa</small></footer>
    {installHelp&&<div className="fp-modal-backdrop" onClick={()=>setInstallHelp(false)}><div className="fp-modal" onClick={e=>e.stopPropagation()}><button className="fp-modal-close" onClick={()=>setInstallHelp(false)} aria-label="Fechar"><X/></button><span className="fp-brand-icon"><Download/></span><h3>Instale o FitPulse</h3><p>Abra o menu do navegador e escolha <b>“Instalar aplicativo”</b> ou <b>“Adicionar à tela inicial”</b>. No iPhone, use o Safari e toque em Compartilhar.</p><button className="fp-primary" onClick={()=>setInstallHelp(false)}>Entendi <Check size={17}/></button></div></div>}
  </main>;
}
